<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\SubCategory;

class SubCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Storage and home organization
        SubCategory::create(['name' => 'Dressers & storage drawers', 'title' => 'Drawers where clothes won’t hide', 'description' => 'A dresser that suits you, your clothes and your space means no more cold mornings searching for your socks. Ours come in styles that match our wardrobes and in different sizes so you can use them around your home, even in a narrow hall. For maximum organization, use SKUBB fabric boxes to sort out your stuff inside the drawers', 'id_category' => 1]);
        SubCategory::create(['name' => 'Wardrobes & closets', 'title' => 'Getting the best PAX wardrobe for you', 'description' => 'High-quality PAX wardrobes come in lots of styles and sizes and with a big range of interior organizers. So, you can choose what’s best for you, your space, and your clothes', 'id_category' => 1]);
        SubCategory::create(['name' => 'Sideboards, buffets & sofa tables', 'title' => 'Sideboards and buffets for extra storage', 'description' => 'Looking for a hall table to welcome you home (and take your mail) or a place for your drink by the sofa? Our occasional tables, sideboards and buffets come in modern and traditional styles with various finishes. They all have room to show off what you want on top, but some have doors and drawers for hiding things, too. Put them against the wall of any room for instant added storage, or use one as a room divider to break up a larger space, creating different activity areas', 'id_category' => 1]);
        // Textiles
        SubCategory::create(['name' => 'Bedding', 'title' => 'A good nights sleep for your rest', 'description' => 'Even if higher temperatures aren’t here quite yet, you can still give spring a head start indoors. Treat your bedroom to a textile makeover - and feel the warmth spread.', 'id_category' => 2]);
        SubCategory::create(['name' => 'Curtains & blinds', 'title' => 'Curtains and blinds help you night and day', 'description' => 'Whatever you’re doing, you can do it better with curtains and blinds. They can block out light to help you sleep, keep the sun off your TV so you don’t miss anything in your favourite shows, make evenings cozier when you want to relax, and more.', 'id_category' => 2]);
        SubCategory::create(['name' => 'Bathroom textiles', 'title' => 'Towels and textiles for a fresh bathroom', 'description' => 'When other parts of your home get a spring makeover, why not include your bathroom in the effort? Replacing worn towels and mismatching textiles with coordinated ones will quickly make your bathroom spring fresh, too.', 'id_category' => 2]);
        // Home decor
        SubCategory::create(['name' => 'Mirrors', 'title' => 'Let your mirrors reflect your style', 'description' => 'Why not include mirrors as part of your home’s decor? Some mirrors even double as handy knobs for hanging clothes - practical and pretty. Mix and match and play around with placement to create a statement wall that is as stylish as your outfit of the day.', 'id_category' => 3]);
        SubCategory::create(['name' => 'Candle holders & candles', 'title' => 'Scented candles and a fragrance of spring', 'description' => 'Spring is in the air, and with it a whole spectrum of lovely smells. If flowers aren’t enough - or if they make you sneeze - scented candles can help spread the arrival of the season throughout your home.', 'id_category' => 3]);
        SubCategory::create(['name' => 'Wall decor', 'title' => 'Love it? Frame it!', 'description' => ' We have a huge assortment of ready-to-hang prints, or you could frame personal photos, artwork and collected objects to surround yourself with smile-inducing mementos. We have loads of frame colours and sizes to choose from to make your home instantly more you.', 'id_category' => 3]);
        // Lighting
        SubCategory::create(['name' => 'Light fixtures & lamps', 'title' => 'Bring a forgotten corner out of the dark', 'description' => 'Lighting is here, there and everywhere. And it’s always ready to help you read a book, slice a carrot or grab your blue (not black) socks. We have lots of lamps and lights to make your home brighter, especially energy-saving ones for a brighter future, too', 'id_category' => 4]);
        SubCategory::create(['name' => 'Smart lighting', 'title' => 'Total control with just one switch', 'description' => 'With smart lighting, you can change the atmosphere in your home with the touch of a button. One remote control puts you in charge of up to 10 different wireless LED lights. Dim them, turn them on or off, and change the warmth of their glow. Our smart lighting range includes wireless LED bulbs, panels, and doors for furniture too. Combine them in your home any way you like and control them with our easy-to-use remote control.', 'id_category' => 4]);
        SubCategory::create(['name' => 'LED light bulbs', 'title' => 'Ever wonder what’s in energy-saving LED bulbs?', 'description' => 'Among other things, there’s a circuit board and tiny, rice-sized diodes. In fact, IKEA only sells LED lighting, saving up to 85% of energy (and saving you money too) compared to halogen or old incandescent bulbs. We have from dimmable bulbs to decorative light bulbs, like the super trendy edison bulbs. And all our LED bulbs are really affordable too', 'id_category' => 4]);
        // Outdoor
        SubCategory::create(['name' => 'Outdoor furniture', 'title' => 'Spend more time outdoors', 'description' => 'Discover our wide range of patio & outdoor furniture - we have everything from smaller, lightweight aluminum furniture for the balcony, to a variety of sizes and materials, like rattan and solid wood furniture, for your spacious patio. Find the ones that suit your style and space and enjoy outdoor living!', 'id_category' => 5]);
        SubCategory::create(['name' => 'Outdoor accessories', 'title' => 'More confort outdoors', 'description' => 'Bring some indoor comfort outside with outdoor accessories & fabrics, like these weather-resistant rugs. They’re an easy, budget-friendly way to renew your space and add a softer touch. And if you want to protect outside furniture and keep it looking fresh for longer, try our tough waterproof covers.', 'id_category' => 5]);
        SubCategory::create(['name' => 'Outdoor storage', 'title' => 'Make more room outdoors', 'description' => 'When the sun shines, we move outside to enjoy it. And so does a lot of stuff. So we have outdoor storage and outdoor storage benches for things like garden tools and shelves that turn a balcony into a multi-storey garden. And also our versatile HYLLIS outdoor shelving units with transparent covers, where you can grow, store and show things off outside or inside your home.', 'id_category' => 5]);
        // Pots & plants 
        SubCategory::create(['name' => 'Plants & flowers', 'title' => 'Growing happiness', 'description' => 'Leave it to a new set of plants to refresh and decorate any space. Going with artificial plants lets you create the same effect - only they’re just as happy without sunlight, and require virtually no maintenance.', 'id_category' => 6]);
        SubCategory::create(['name' => 'Flower pots & stands', 'title' => 'Take a seat, plants!', 'description' => 'Give your plants a spot in the sun. And everyone near them a green boost in the process. Since window space is a limited resource, adding a surface - like a bench or a side table - close to the sill enables you to spread the joy.', 'id_category' => 6]);
        SubCategory::create(['name' => 'Watering cans', 'title' => 'Plants need water.', 'description' => 'And a watering can is a lot more practical and less splashy than showering them from your milk jug or a cup. Whether it’s a spray bottle to spritz your plants or a metal watering can that adds its deco powers to your room, you’ll find the right watering cans right here.', 'id_category' => 6]);
        // Kitchen & appliances
        SubCategory::create(['name' => 'Kitchen interior organizers', 'title' => 'Imagine finding your potato peeler when you need it', 'description' => 'Kitchen storage organizers turn chaos into things of beauty and efficiency. From cupboard organizers to cutlery trays, these unsung heroes will help you declutter your everyday and make your cooking routine sing.', 'id_category' => 7]);
        SubCategory::create(['name' => 'Pantry', 'title' => 'Ingredients to pantry organization', 'description' => 'Meals get made much quicker when you can quickly find the right ingredients. Our pantry storage puts all your kitchen supplies in instant view. You can choose the right pantry shelves for your needs to make the most of the space you have and use clip-on baskets to organise smaller items.', 'id_category' => 7]);
        SubCategory::create(['name' => 'Wall storage', 'title' => 'Keep your kitchenware in reach', 'description' => 'When cabinet and drawer space is in short supply, use our kitchen wall storage & wall racks to fill the gaps. Create your own solutions with rails, shelves and magnetic strips that make everything easier to find & grab; they also help you make a style statement.', 'id_category' => 7]);
        // Bathroom
        SubCategory::create(['name' => 'Bathroom accessories', 'title' => 'Personalize your bathroom sink with soap dispensers and soap dishes', 'description' => 'Even the smallest things can make a great impact. That is especially true with our range of soap dispensers and soap dishes. We’ve got something for the bold, the minimalist and everyone in between.', 'id_category' => 8]);
        SubCategory::create(['name' => 'Bathroom laundry', 'title' => 'Get laundry sorted', 'description' => 'Whether your clothes are wet or dry, make sure you have the right tools for the job.', 'id_category' => 8]);
        SubCategory::create(['name' => 'Bathroom storage', 'title' => 'Tidy up your bathroom routine', 'description' => 'On busy mornings, every minute counts. Knowing where everything is - like having designated drawers, boxes and organizers - can shave off valuable time from your morning routine, and make the start of your day just that much better.', 'id_category' => 8]);
        // Home electronics
        SubCategory::create(['name' => 'Mobile & tablet accessories', 'title' => 'Mobile devices little helpers', 'description' => 'Every day our smartphones and tablets patiently sit inside our pockets, ready to help us whenever we need them. But in order to do that, these little heroes need their own little helpers that make sure they stay powered or get supported. That is why we offer many tablet and phone accessories, all with different functionalities and unique designs.', 'id_category' => 9]);
        SubCategory::create(['name' => 'Cords & chargers', 'title' => 'Stay powered up!', 'description' => 'They are called “mobile” devices for a reason - you can easily carry them with you and use them whenever and wherever you want. They are super useful and super handy - at least until they run out of battery. That is why we offer a range of power cables, phone chargers, power banks and more that help you make sure your devices stay fully charged and powered up.', 'id_category' => 9]);
        SubCategory::create(['name' => 'Speakers', 'title' => 'Release the sound of your home', 'description' => 'Everything in life is better with music! Our wireless Bluetooth® and WiFi speakers are designed to harmonize with your décor and boast powerful sound to create atmosphere in your space.  The affordable ENEBY Bluetooth® speakers range includes portable speakers and built-in options, as well as larger speakers suitable for wall-mounting.  For the audiophiles, there’s our new SYMFONISK range, which includes a bookshelf speaker sand a table lamp speaker. Created in collaboration with Sonos, these stylish wireless speakers allow you to enjoy stereo sound by using two identical speakers, or create a multiroom system, so you can play different music in each room or the same everywhere.', 'id_category' => 9]);
    }
}
